# Используем образ с MySQL
FROM mysql:latest

# Устанавливаем переменные окружения для MySQL
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Запускаем MySQL
CMD ["mysqld"]
